ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += hts221
endif

ifeq (,$(filter nrfmin,$(USEMODULE)))
  ifneq (,$(filter gnrc_netdev_default,$(USEMODULE)))
    USEPKG += nordic_softdevice_ble
  endif
endif

ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
endif

include $(RIOTBOARD)/common/nrf52/Makefile.dep
